"""Add password_hash field to user models

Revision ID: 3a8f8c7b2a87
Revises: add_equip_name_idx
Create Date: 2026-01-02 06:55:50.359036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8f8c7b2a87'
down_revision = 'add_equip_name_idx'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码Hash值'))
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratory', ['manage_scope'], ['id'])

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratory', ['lab_id'], ['id'])

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'equipment', ['equip_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码Hash值'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratory', ['lab_id'], ['id'])
        batch_op.create_foreign_key(None, 'teacher', ['t_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码Hash值'))
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'laboratory', ['lab_id'], ['id'])

    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment', ['equip_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeslot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'equipment', ['equip_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'laboratory', ['lab_id'], ['id'], referent_schema='test')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'laboratory', ['lab_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'teacher', ['t_id'], ['id'], referent_schema='test')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'teacher', ['teacher_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'student', ['student_id'], ['id'], referent_schema='test')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'equipment', ['equip_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'laboratory', ['lab_id'], ['id'], referent_schema='test')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'laboratory', ['manage_scope'], ['id'], referent_schema='test')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
